"""empty message

Revision ID: 63bf3b4d4a94
Revises: 
Create Date: 2026-03-13 00:44:39.956893
"""

from alembic import op
import sqlalchemy as sa


revision = '63bf3b4d4a94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('timetable_mode_name', sa.String(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_remote_available', sa.Boolean(), nullable=False),
    sa.Column('is_hot', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_vacancies_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    # ### end Alembic commands ###
